version: 2
project_name: cardano-validator-watcher
before:
  hooks:
    - go mod tidy
builds:
  - id: cardano-validator-watcher
    main: cmd/watcher/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - format: tar.gz
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    files:
      - none*
changelog:
  disable: true