pools:
  - instance: instance_1
    id: pool_bench32_id
    name: pool_name
    key: config/pool_name.vrf.skey
    exclude: false
  - instance: instance_2
    id: pool_bench32_id
    name: pool_name
    key: config/pool_name.vrf.skey
    exclude: true
    allow-empty-slots: true
network: mainnet
block-watcher:
  enabled: true
  refresh-interval: 60
pool-watcher:
  enabled: true
  refresh-interval: 60
network-watcher:
  enabled: true
  refresh-interval: 60
status-watcher:
  refresh-interval: 15
database:
  path: watcher.db
blockfrost:
  project-id: "thisissecret"
  endpoint: https://cardano-mainnet.blockfrost.io/api/v0
  max-routines: 10
  timeout: 60
http:
  host: "0.0.0.0"
  port: 8080
cardano:
  config-dir: config
  socket-path: /tmp/cardano.socket
  timezone: UTC